name: mmw-cavity-paper-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - aenum=3.1.15
  - aiohttp=3.9.0b0
  - aiosignal=1.3.1
  - alabaster=1.0.0
  - anyio=4.4.0
  - aom=3.9.0
  - appnope=0.1.3
  - arrow=1.3.0
  - asteval=0.9.32
  - asttokens=2.4.1
  - atk-1.0=2.38.0
  - attrs=23.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bibtexparser=1.4.3
  - blosc=1.21.6
  - bokeh=3.3.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.2
  - c-blosc2=2.15.0
  - ca-certificates=2025.7.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.18.0
  - certifi=2025.7.9
  - cffi=1.16.0
  - cfgv=3.3.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - cirq-core=1.3.0
  - cirq-google=1.3.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.3.0
  - control=0.10.1
  - cryptography=41.0.5
  - cssbeautifier=1.15.1
  - cycler=0.12.1
  - dataclasses=0.8
  - dav1d=1.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - deprecated=1.2.18
  - deprecation=2.1.0
  - distlib=0.3.8
  - djlint=1.35.2
  - docstring_parser=0.16
  - docutils=0.21.2
  - duet-python=0.2.9
  - editorconfig=0.12.3
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.4
  - fake-useragent=2.0.3
  - filelock=3.13.3
  - flake8=6.1.0
  - fltk=1.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.45.0
  - free-proxy=1.1.3
  - freeimage=3.18.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - future=0.18.3
  - gdk-pixbuf=2.42.12
  - gettext=0.21.1
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.42
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - gmsh=4.12.2
  - google-api-core=1.31.5
  - google-api-core-grpc=1.31.5
  - google-auth=1.35.0
  - googleapis-common-protos=1.61.0
  - graphite2=1.3.13
  - grpcio=1.60.1
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.2.0
  - h5py=3.12.1
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - html-tag-names=0.1.2
  - html-void-elements=0.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - identify=2.5.35
  - idna=3.4
  - imagecodecs=2024.6.1
  - imageio=2.34.1
  - imagesize=1.4.1
  - imath=3.1.9
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - iniconfig=2.0.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipywidgets=8.1.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - jsbeautifier=1.14.9
  - json5=0.9.25
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.9
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.8.0
  - libcxx=19.1.3
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgrpc=1.60.1
  - libhwy=1.1.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.3
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.64.0
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.44
  - libpq=16.3
  - libprotobuf=4.25.1
  - libraw=0.21.1
  - libre2-11=2023.06.02
  - librsvg=2.58.2
  - libsodium=1.0.18
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=17.0.5
  - lmfit=1.2.2
  - lxml=5.3.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - narwhals=1.46.0
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=2.8.8
  - nodeenv=1.8.0
  - nspr=4.35
  - nss=3.105
  - numpy=1.26.4
  - occt=7.7.2
  - openexr=3.2.1
  - openfermion=1.5.1
  - openjpeg=2.5.2
  - openssl=3.5.1
  - outcome=1.3.0.post0
  - packaging=23.2
  - pandas=2.2.3
  - pango=1.50.14
  - parso=0.8.3
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=23.3.1
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.0.0
  - plotly=6.2.0
  - pluggy=1.4.0
  - ply=3.11
  - portaudio=19.6.0
  - pre-commit=3.7.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - proto-plus=1.25.0
  - protobuf=4.25.1
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pubchempy=1.0.4
  - pure_eval=0.2.2
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pyface=8.0.0
  - pyflakes=3.1.0
  - pygments=2.17.2
  - pyopenssl=23.3.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtgraph=0.13.3
  - pyserial=3.5
  - pysocks=1.7.1
  - pytest=8.1.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.21.1
  - python-gmsh=4.12.2
  - python-sounddevice=0.4.6
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyvisa=1.14.1
  - pywavelets=1.7.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qhull=2020.2
  - qt-main=5.15.8
  - qtpy=2.4.1
  - rapidjson=1.1.0.post20240409
  - rav1e=0.6.6
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.9.11
  - requests=2.31.0
  - roman-numerals-py=3.1.0
  - rpds-py=0.26.0
  - rsa=4.9
  - scholarly=1.7.11
  - scikit-image=0.24.0
  - scikit-rf=1.4.0
  - scipy=1.14.1
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - selenium=4.16.0
  - selenium-manager=4.16.0
  - setuptools=68.2.2
  - setuptools-scm=8.0.4
  - sip=6.7.12
  - six=1.16.0
  - slycot=0.6.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - svt-av1=2.1.0
  - sympy=1.12
  - tifffile=2024.5.22
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - traits=6.4.3
  - traitsui=8.0.0
  - trio=0.24.0
  - trio-websocket=0.12.2
  - typed-argument-parser=1.10.0
  - types-python-dateutil=2.9.0.20241206
  - types-requests=2.31.0.20240403
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_inspect=0.9.0
  - tzdata=2023c
  - tzlocal=5.3
  - ukkonen=1.0.1
  - uncertainties=3.1.7
  - urllib3=2.1.0
  - virtualenv=20.25.1
  - wcwidth=0.2.12
  - wheel=0.41.3
  - widgetsnbextension=4.0.9
  - wrapt=1.17.2
  - wsproto=1.2.0
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - arc-alkali-rydberg-calculator==3.5.0
